# Generated by Django 5.0.14 on 2026-02-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCampaignStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ctr", models.FloatField(default=0.0)),
                ("conversion_rate", models.FloatField(default=0.0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "daily_campaign_stats",
                "unique_together": {("campaign", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyMerchantStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("conversations_started", models.IntegerField(default=0)),
                ("conversations_converted", models.IntegerField(default=0)),
                ("messages_sent", models.IntegerField(default=0)),
                ("clicks_total", models.IntegerField(default=0)),
                ("clicks_valid", models.IntegerField(default=0)),
                ("clicks_fraudulent", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                (
                    "revenue_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ctr", models.FloatField(default=0.0)),
                ("conversion_rate", models.FloatField(default=0.0)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "daily_merchant_stats",
                "unique_together": {("merchant", "date")},
            },
        ),
        migrations.CreateModel(
            name="HourlyClickStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField()),
                ("clicks", models.IntegerField(default=0)),
                ("valid_clicks", models.IntegerField(default=0)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hourly_click_stats",
                "unique_together": {("merchant", "hour")},
            },
        ),
    ]
