# Generated by Django 5.0.14 on 2026-02-24 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("conversations", "0001_initial"),
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("referer", models.URLField(blank=True, max_length=2048)),
                ("country_code", models.CharField(blank=True, max_length=5)),
                ("is_fraudulent", models.BooleanField(default=False)),
                ("fraud_score", models.FloatField(default=0.0)),
                ("fraud_reasons", models.JSONField(default=list)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "click_events",
            },
        ),
        migrations.CreateModel(
            name="FraudFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("rate_limit", "Rate Limit"),
                            ("token_reuse", "Token Reuse"),
                            ("low_dwell", "Low Dwell Time"),
                            ("ip_cluster", "IP Cluster"),
                            ("bot_ua", "Bot User Agent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "click_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_flags",
                        to="tracking.clickevent",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fraud_flags",
            },
        ),
        migrations.CreateModel(
            name="RedirectToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("destination_url", models.URLField(max_length=2048)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirect_tokens",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merchants.sku"
                    ),
                ),
            ],
            options={
                "db_table": "redirect_tokens",
            },
        ),
        migrations.AddField(
            model_name="clickevent",
            name="redirect_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="tracking.redirecttoken",
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["clicked_at"], name="click_event_clicked_5f94d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["redirect_token", "ip_address"],
                name="click_event_redirec_98b1bd_idx",
            ),
        ),
    ]
