# Generated by Django 5.0.14 on 2026-02-24 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("qualifying", "Qualifying"),
                            ("narrowing", "Narrowing"),
                            ("pitching", "Pitching"),
                            ("closing", "Closing"),
                            ("objection_handling", "Objection Handling"),
                            ("followup", "Follow Up"),
                            ("handed_off", "Handed Off"),
                            ("ended", "Ended"),
                        ],
                        default="greeting",
                        max_length=30,
                    ),
                ),
                ("context_json", models.JSONField(default=dict)),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                ("is_opted_out", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ab_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.abtestvariant",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "handed_off_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "recommended_skus",
                    models.ManyToManyField(blank=True, to="merchants.sku"),
                ),
            ],
            options={
                "db_table": "conversations",
            },
        ),
        migrations.CreateModel(
            name="FollowUpSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("message_template", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "followup_schedules",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("agent", "Agent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                ("twilio_sid", models.CharField(blank=True, max_length=64)),
                ("media_url", models.URLField(blank=True)),
                ("stage_at_send", models.CharField(blank=True, max_length=30)),
                ("openai_tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ("created_at",),
            },
        ),
    ]
