# Generated by Django 5.0.14 on 2026-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="industry",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("fashion", "Fashion & Clothing"),
                    ("home", "Home & Living"),
                    ("health", "Health & Wellness"),
                    ("food", "Food & Beverages"),
                    ("beauty", "Beauty & Personal Care"),
                    ("sports", "Sports & Fitness"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
